FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    locales \
    curl \
    git \
    python3-pip \
    python3-colcon-common-extensions \
    build-essential \
    cmake \
    vim

# ROS installation here later
